### ISSUE TITLE
请求增加用户SESSDATA授权付费信息的方式

### ISSUE THREAD

**Issue by clbclby** [vooidzero/B23Downloader#10]
希望可以增加一种通过用户SESSDATA授权付费信息的方式，多谢您，辛苦了！真的很需要这个功能，拜托拜托！

**Comment by vooidzero** [comment]
目前登录信息和下载任务保存在 `%APPDATA%\VoidZero\B23Downloader.ini`（%APPDATA%变量展开后是`C:\Users\xxx\AppData\Roaming`，这个文件也就几KB，放在C盘只是为了开发方便）
文件内容是：
```
[General]
tasks=@ByteArray([])
cookies="..."
lastDir=...
```
你没登录的话 `cookies="..."` 那一行就没有，可以自行添加一行 `cookies="SESSDATA=xxx; domain=.bilibili.com; path=/"`

---

目前有bug的话我可以看看修一修，但是没有心情加feature。往后要是再开发的话 .ini 会挪到程序所在文件夹里，这个SESSDATA也可以考虑放在高级设置里。

**Comment by clbclby** [comment]
多谢，辛苦了
