### ISSUE TITLE
添加Android版

### ISSUE THREAD

**Issue by FallenDown0** [vooidzero/B23Downloader#2]
希望开发者可以添加Android版

**Comment by vooidzero** [comment]
@FallenDown0 

用的是 Qt，应该能编译出安卓的，不过桌面端的 UI 换到移动端肯定是糟糕的。本人无安卓开发经验也没有需求，没功夫做这个。

**Comment by FallenDown0** [comment]
> @FallenDown0
> 
> 用的是 Qt，应该能编译出安卓的，不过桌面端的 UI 换到移动端肯定是糟糕的。本人无安卓开发经验也没有需求，没功夫做这个。

好的，感谢开发者~o(〃'▽'〃)o
