### ISSUE TITLE
非大会员只能下载会员视频预览1分钟的内容吗，不是番剧，综艺那种的

### ISSUE THREAD

**Issue by shemengjia** [vooidzero/B23Downloader#37]
非大会员只能下载会员视频预览1分钟的内容吗，不是番剧，综艺那种的

**Comment by vooidzero** [comment]
是的，并不能超越大会员/付费的限制。

这种情况应该是禁用下载不可选中，之前的版本没有正确判断导致了下载预览视频这一现象
