### ISSUE TITLE
当漫画标题开头或结尾有空格时会无法下载

### ISSUE THREAD

**Issue by Telloyee** [vooidzero/B23Downloader#4]
目前只试过漫画，有这个问题，不知道直播和视频标题有/会不会也下载不了
比如说这个：
https://manga.bilibili.com/detail/mc25632

**Comment by vooidzero** [comment]
@Telloyee 感谢反馈。
斜杠的问题在开发最初的时候就考虑了：标题中的 `\/:*?"<>|` 会相应地替换为全角字符。

这里的问题其实是合成标题的时候末尾有空格，然后创建了一个末尾有空格的文件夹，之后在这个文件夹里创建文件失败（小提一句，这个在 Linux 平台上是没问题的）。

Release 已更新，请先删除该漫画下载任务以及文件夹（这文件夹好像不太好删？），然后才能下载该漫画

---

解决方法：在创建下载任务时移去标题开头和末尾的空格。

相关文件：`utils.cpp`
```diff
QString Utils::legalizedFileName(QString title)
{
-    return title.replace('\\', u'＼').replace('/', u'／').replace(':', u'：')
+    return title.simplified()
+            .replace('\\', u'＼').replace('/', u'／').replace(':', u'：')
             .replace('*', u'＊').replace('?', u'？').replace('"', u'“')
             .replace('<', u'＜').replace('>', u'＞').replace('|', u'｜');
}
```
