### ISSUE TITLE
下载的flv是网站的默认视频格式吗

### ISSUE THREAD

**Issue by mghj** [vooidzero/B23Downloader#5]
你好，下载的flv是网站的默认视频格式吗？

**Comment by vooidzero** [comment]
B 站现在都是用 DASH 音视频分流，对应的封装格式为  fmp4 (fragmented mp4)，不过 FLV 还是一直被支持的。
这里下载 FLV 是因为音视频在一个文件里，实现简单。

FLV 的问题是官方标准不支持 HEVC (H265)
- 一般来讲 B 站 HEVC 在同画质下体积是 AVC (H264) 的一半
- B 站视频 AVC 的天花板画质为 4K，再往上（HDR，杜比视界、8K）就只有 HEVC。即 FLV 的天花板画质是 4K。

其他 B 站下载器有支持 DASH 下载的，他们的实现方式是音视频两个文件下载完成后用 ffmpeg 或 mp4box 混流成一个文件。这样做的缺点是下载完成前最多只能单个播放视频/音频。我想实现边下载边混流（Issue #1），还是挺麻烦的。
