### ISSUE TITLE
下载漫画《非人哉》时最多只能显示到813章节

### ISSUE THREAD

**Issue by Leonardo-Jodeve** [vooidzero/B23Downloader#54]
漫画地址：https://manga.bilibili.com/detail/mc24442
1.截至提交本Issue，最新话为832
    //但是B23D只能显示到813
2.官方客户端、网页端均能正常观看漫画
    //不是付费或者账号权限不够，这是一本免费漫画
3.该问题目前只在这一本漫画中可以复现

**Comment by vooidzero** [comment]
- duplicate issue of #30
