### ISSUE TITLE
非大会员不能下载1080p60f视频？

### ISSUE THREAD

**Issue by Giorie** [vooidzero/B23Downloader#6]
选择了1080p60且原视频有该选项 但是实际上下载的视频只有30帧 是非大会员的原因么

**Comment by vooidzero** [comment]
是的，并不能超越大会员/付费的限制。

这个应该给出描述清除且醒目的提示，不过算了，懒得搞了。

**Comment by chengyiqun** [comment]
没有大会员, 最高画质的源链接都无法获取的
