### ISSUE TITLE
Win11能用嗎?求助

### ISSUE THREAD

**Issue by ycculock** [vooidzero/B23Downloader#60]
我買了新電腦,系統是win11,但除了小短片能載以外,長的影片如1小時大檔案,下載就會直接顯示:打開文件失敗。
但我win10舊電腦就能下載,請問有什麼解決方法嗎?
我兩個版本都試過了~頭好痛R,希望作者今年春暖花開就在QQ

**Comment by vooidzero** [comment]
- 我用Win11是正常的，不知道你那边是什么情况。

- 这个项目已经很久没有维护，推荐你用其他工具下载B站视频，比如 [leiurayer/downkyi (哔哩下载姬)](https://github.com/leiurayer/downkyi)
